baseURL = 'https://sonichighway.band/'
languageCode = 'en-us'
title = 'Sonic Highway'
theme = 'hugo-split-theme'


[params]
[params.visual.image]
  enable = true
  file = "images/acapella-1.jpeg"
  position = "center center"

[params.custom.css]
  enable = true
